name: rlib

channels:
  - anaconda
  - pytorch
  - conda-forge

dependencies:
  - python
  - pytorch
  - numpy
  - matplotlib
  - tensorflow
  - pip:
    - atari-py
    - gym
    - imageio
    - sphinx-gallery
    - sphinxcontrib-napoleon
    - sphinxcontrib-bibtex
    - sphinxcontrib-inlinesyntaxhighlight
